### ISSUE TITLE
啥时候把训练模型类公开出来

### ISSUE THREAD

**Issue by awepoker** [chenwei-zhao/captcha-recognizer#13]

**Comment by chenwei-zhao** [comment]
仅供参考，根据个人训练情况调整

## 训练脚本如下

```python3
from ultralytics import YOLO

model = YOLO("models/yolov8s.pt")

model.train(
    data="dataset.yaml",
    epochs=500,
    device='cpu',
    name="<your name>",
    batch=16,
    workers=8,
    imgsz=416,
    patience=50,
)

path = model.export(format="onnx")  # export the model to ONNX format
print(path)
````


## dataset.yaml

```yaml
path: <root dir>
train: images/train
val: images/val
test: images/test

names:
    0: t
    1: f
    2: s
```

## 分类
- t: 滑块验证码实际缺口
- f: 滑块验证码障碍缺口
- s: 滑块验证码的移动滑块
